/*
Generated by LwipMibCompiler
*/

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#include "mobanetclocksv2-mib.h"
#include "lwip/apps/snmp.h"
#include "lwip/apps/snmp_core.h"
#include "lwip/apps/snmp_scalar.h"
#include "lwip/apps/snmp_table.h"


/* --- mbnscNet 1.3.6.1.4.1.13842.6.2.1 ----------------------------------------------------- */
static u16_t mbnscnetgen_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static snmp_err_t mbnscnetgen_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static snmp_err_t mbnscnetgen_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static const struct snmp_scalar_array_node_def mbnscnetgen_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNetGenMAC */ 
  {2, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetGenIPMode */ 
  {3, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetGenIPNameserver */ 
  {4, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetGenTZClientPort */ 
  {5, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetGenConfigPort */ 
  {6, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNetGenSnmpMode */ 
  {7, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetGenMulticastMode */ 
  {8, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetGenHostname */ 
  {9, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNetGenCommMode */ 
  {10, SNMP_ASN1_TYPE_IPADDR, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetGenMCastGrpIP */ 
  {100, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetGenConfigCmd */ 
  {101, SNMP_ASN1_TYPE_TIMETICKS, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNetGenConfigChangedTime */ 
};
static const struct snmp_scalar_array_node mbnscnetgen_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(1, mbnscnetgen_scalars_nodes, mbnscnetgen_scalars_get_value, mbnscnetgen_scalars_set_test, mbnscnetgen_scalars_set_value);

static u16_t mbnscnetipv4_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static snmp_err_t mbnscnetipv4_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static snmp_err_t mbnscnetipv4_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static const struct snmp_scalar_array_node_def mbnscnetipv4_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_IPADDR, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetIPv4Addr */ 
  {2, SNMP_ASN1_TYPE_IPADDR, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetIPv4Mask */ 
  {3, SNMP_ASN1_TYPE_IPADDR, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetIPv4Gateway */ 
  {4, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetIPv4DHCPMode */ 
  {100, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetIPv4ConfigCmd */ 
  {101, SNMP_ASN1_TYPE_TIMETICKS, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNetIPv4ConfigChangedTime */ 
};
static const struct snmp_scalar_array_node mbnscnetipv4_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(2, mbnscnetipv4_scalars_nodes, mbnscnetipv4_scalars_get_value, mbnscnetipv4_scalars_set_test, mbnscnetipv4_scalars_set_value);

static u16_t mbnscnetipv6_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static snmp_err_t mbnscnetipv6_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static snmp_err_t mbnscnetipv6_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static const struct snmp_scalar_array_node_def mbnscnetipv6_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNetIPv6AddrLocal */ 
  {2, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNetIPv6AddrAuto */ 
  {3, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNetIPv6AddrDHCP */ 
  {4, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetIPv6AddrFix */ 
  {5, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetIPv6Prefix */ 
  {6, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNetIPv6Gateway */ 
  {7, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetIPv6Config */ 
  {100, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscNetIPv6ConfigCmd */ 
  {101, SNMP_ASN1_TYPE_TIMETICKS, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNetIPv6ConfigChangedTime */ 
};
static const struct snmp_scalar_array_node mbnscnetipv6_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(3, mbnscnetipv6_scalars_nodes, mbnscnetipv6_scalars_get_value, mbnscnetipv6_scalars_set_test, mbnscnetipv6_scalars_set_value);

static const struct snmp_node *const mbnscnet_subnodes[] = {
  &mbnscnetgen_scalars.node.node,
  &mbnscnetipv4_scalars.node.node,
  &mbnscnetipv6_scalars.node.node
};
static const struct snmp_tree_node mbnscnet_treenode = SNMP_CREATE_TREE_NODE(1, mbnscnet_subnodes);

/* --- mbnscAdditionalDigitalClockModes 1.3.6.1.4.1.13842.6.2.4.30 ----------------------------------------------------- */
static u16_t mbnscsensors_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static snmp_err_t mbnscsensors_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static snmp_err_t mbnscsensors_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static const struct snmp_scalar_array_node_def mbnscsensors_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscSensorsTempActivation */ 
  {2, SNMP_ASN1_TYPE_IPADDR, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscSensorsTemp1IPAddr */ 
  {3, SNMP_ASN1_TYPE_IPADDR, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscSensorsTemp2IPAddr */ 
  {100, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscSensorsConfigCmd */ 
  {101, SNMP_ASN1_TYPE_TIMETICKS, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscSensorsConfigChangedTime */ 
};
static const struct snmp_scalar_array_node mbnscsensors_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(1, mbnscsensors_scalars_nodes, mbnscsensors_scalars_get_value, mbnscsensors_scalars_set_test, mbnscsensors_scalars_set_value);

static u16_t mbnscda_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static snmp_err_t mbnscda_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static snmp_err_t mbnscda_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static const struct snmp_scalar_array_node_def mbnscda_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDASecondCircleDisplay */ 
  {100, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDAConfigCmd */ 
  {101, SNMP_ASN1_TYPE_TIMETICKS, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscDAConfigChangedTime */ 
};
static const struct snmp_scalar_array_node mbnscda_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(2, mbnscda_scalars_nodes, mbnscda_scalars_get_value, mbnscda_scalars_set_test, mbnscda_scalars_set_value);

static u16_t mbnscdk_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static snmp_err_t mbnscdk_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static snmp_err_t mbnscdk_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static const struct snmp_scalar_array_node_def mbnscdk_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKFirstLanguage */ 
  {2, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKSecondLanguage */ 
  {3, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKThirdLanguage */ 
  {4, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKTempUnitSecondLang */ 
  {5, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKTempUnitThirdLang */ 
  {6, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKAutoLangSwitchOver */ 
  {7, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKNumOfCharsForWeekday */ 
  {8, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKNamesFormatDisplay */ 
  {9, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKTemp1DescriptEnable */ 
  {10, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKTemp1Description */ 
  {11, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKTemp2DescriptEnable */ 
  {12, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKTemp2Description */ 
  {13, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKWorldTimeZone1 */ 
  {14, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKWorldTimeZone1Description */ 
  {15, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKWorldTimeZone2 */ 
  {16, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKWorldTimeZone2Description */ 
  {17, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKWorldTimeZone3 */ 
  {18, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKWorldTimeZone3Description */ 
  {19, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKWorldTimeZone4 */ 
  {20, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKWorldTimeZone4Description */ 
  {21, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKWorldTimeZone5 */ 
  {22, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKWorldTimeZone5Description */ 
  {23, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKAutoTimeZoneSwitchOver */ 
  {100, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscDKConfigCmd */ 
  {101, SNMP_ASN1_TYPE_TIMETICKS, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscDKConfigChangedTime */ 
};
static const struct snmp_scalar_array_node mbnscdk_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(3, mbnscdk_scalars_nodes, mbnscdk_scalars_get_value, mbnscdk_scalars_set_test, mbnscdk_scalars_set_value);

static const struct snmp_node *const mbnscadditionaldigitalclockmodes_subnodes[] = {
  &mbnscsensors_scalars.node.node,
  &mbnscda_scalars.node.node,
  &mbnscdk_scalars.node.node
};
static const struct snmp_tree_node mbnscadditionaldigitalclockmodes_treenode = SNMP_CREATE_TREE_NODE(30, mbnscadditionaldigitalclockmodes_subnodes);

/* --- mbnscNMI 1.3.6.1.4.1.13842.6.2.4.40.1 ----------------------------------------------------- */
static u16_t mbnscnmi_treenode_get_value(struct snmp_node_instance *instance, void *value);
static snmp_err_t mbnscnmi_treenode_set_test(struct snmp_node_instance *instance, u16_t len, void *value);
static snmp_err_t mbnscnmi_treenode_set_value(struct snmp_node_instance *instance, u16_t len, void *value);
static const struct snmp_scalar_node mbnscnmidcfcurrentloop_scalar = SNMP_SCALAR_CREATE_NODE(1, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_INTEGER, mbnscnmi_treenode_get_value, mbnscnmi_treenode_set_test, mbnscnmi_treenode_set_value);

static const struct snmp_scalar_node mbnscnmilinedriver_scalar = SNMP_SCALAR_CREATE_NODE(2, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_INTEGER, mbnscnmi_treenode_get_value, mbnscnmi_treenode_set_test, mbnscnmi_treenode_set_value);

static const struct snmp_scalar_node mbnscnmimobalinemode_scalar = SNMP_SCALAR_CREATE_NODE(3, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_INTEGER, mbnscnmi_treenode_get_value, mbnscnmi_treenode_set_test, mbnscnmi_treenode_set_value);

static const struct snmp_scalar_node mbnscnmimobalineminutehandmode_scalar = SNMP_SCALAR_CREATE_NODE(4, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_INTEGER, mbnscnmi_treenode_get_value, mbnscnmi_treenode_set_test, mbnscnmi_treenode_set_value);

static const struct snmp_scalar_node mbnscnmiactivedcfmode_scalar = SNMP_SCALAR_CREATE_NODE(5, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_INTEGER, mbnscnmi_treenode_get_value, mbnscnmi_treenode_set_test, mbnscnmi_treenode_set_value);

static const struct snmp_scalar_node mbnscnmiconfigcmd_scalar = SNMP_SCALAR_CREATE_NODE(100, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_GAUGE, mbnscnmi_treenode_get_value, mbnscnmi_treenode_set_test, mbnscnmi_treenode_set_value);

static const struct snmp_scalar_node mbnscnmiconfigchangedtime_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(101, SNMP_ASN1_TYPE_TIMETICKS, mbnscnmi_treenode_get_value);

static u16_t mbnscnmisideclockstate_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static const struct snmp_scalar_array_node_def mbnscnmisideclockstate_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock1 */ 
  {2, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock2 */ 
  {3, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock3 */ 
  {4, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock4 */ 
  {5, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock5 */ 
  {6, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock6 */ 
  {7, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock7 */ 
  {8, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock8 */ 
  {9, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock9 */ 
  {10, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock10 */ 
  {11, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock11 */ 
  {12, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscNMISideClock12 */ 
};
static const struct snmp_scalar_array_node mbnscnmisideclockstate_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(20, mbnscnmisideclockstate_scalars_nodes, mbnscnmisideclockstate_scalars_get_value, NULL, NULL);

static const struct snmp_node *const mbnscnmi_subnodes[] = {
  &mbnscnmidcfcurrentloop_scalar.node.node,
  &mbnscnmilinedriver_scalar.node.node,
  &mbnscnmimobalinemode_scalar.node.node,
  &mbnscnmimobalineminutehandmode_scalar.node.node,
  &mbnscnmiactivedcfmode_scalar.node.node,
  &mbnscnmiconfigcmd_scalar.node.node,
  &mbnscnmiconfigchangedtime_scalar.node.node,
  &mbnscnmisideclockstate_scalars.node.node
};
static const struct snmp_tree_node mbnscnmi_treenode = SNMP_CREATE_TREE_NODE(1, mbnscnmi_subnodes);

/* --- mbnscAdditionalInterfaceModes 1.3.6.1.4.1.13842.6.2.4.40 ----------------------------------------------------- */
static const struct snmp_node *const mbnscadditionalinterfacemodes_subnodes[] = {
  &mbnscnmi_treenode.node
};
static const struct snmp_tree_node mbnscadditionalinterfacemodes_treenode = SNMP_CREATE_TREE_NODE(40, mbnscadditionalinterfacemodes_subnodes);

/* --- mbnscMode 1.3.6.1.4.1.13842.6.2.4 ----------------------------------------------------- */
static u16_t mbnscmode_treenode_get_value(struct snmp_node_instance *instance, void *value);
static snmp_err_t mbnscmode_treenode_set_test(struct snmp_node_instance *instance, u16_t len, void *value);
static snmp_err_t mbnscmode_treenode_set_value(struct snmp_node_instance *instance, u16_t len, void *value);
static const struct snmp_scalar_node mbnscmodeswitchinfo_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(1, SNMP_ASN1_TYPE_INTEGER, mbnscmode_treenode_get_value);

static const struct snmp_scalar_node mbnscmodedisplaybrightness_scalar = SNMP_SCALAR_CREATE_NODE(2, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_OCTET_STRING, mbnscmode_treenode_get_value, mbnscmode_treenode_set_test, mbnscmode_treenode_set_value);

static const struct snmp_scalar_node mbnscmodedisplayformat_scalar = SNMP_SCALAR_CREATE_NODE(3, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_OCTET_STRING, mbnscmode_treenode_get_value, mbnscmode_treenode_set_test, mbnscmode_treenode_set_value);

static const struct snmp_scalar_node mbnscmodedisplayalternate_scalar = SNMP_SCALAR_CREATE_NODE(4, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_OCTET_STRING, mbnscmode_treenode_get_value, mbnscmode_treenode_set_test, mbnscmode_treenode_set_value);

static const struct snmp_scalar_node mbnscmodeirlock_scalar = SNMP_SCALAR_CREATE_NODE(6, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_OCTET_STRING, mbnscmode_treenode_get_value, mbnscmode_treenode_set_test, mbnscmode_treenode_set_value);

static const struct snmp_scalar_node mbnscmodetimedispzeros_scalar = SNMP_SCALAR_CREATE_NODE(7, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_OCTET_STRING, mbnscmode_treenode_get_value, mbnscmode_treenode_set_test, mbnscmode_treenode_set_value);

static const struct snmp_scalar_node mbnscmodedatedispzeros_scalar = SNMP_SCALAR_CREATE_NODE(8, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_OCTET_STRING, mbnscmode_treenode_get_value, mbnscmode_treenode_set_test, mbnscmode_treenode_set_value);

static const struct snmp_scalar_node mbnscmodetempunit_scalar = SNMP_SCALAR_CREATE_NODE(9, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_OCTET_STRING, mbnscmode_treenode_get_value, mbnscmode_treenode_set_test, mbnscmode_treenode_set_value);

static const struct snmp_scalar_node mbnscmodeclockopmode_scalar = SNMP_SCALAR_CREATE_NODE(10, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_OCTET_STRING, mbnscmode_treenode_get_value, mbnscmode_treenode_set_test, mbnscmode_treenode_set_value);

static const struct snmp_scalar_node mbnscmodedispderating_scalar = SNMP_SCALAR_CREATE_NODE(12, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_OCTET_STRING, mbnscmode_treenode_get_value, mbnscmode_treenode_set_test, mbnscmode_treenode_set_value);

static const struct snmp_scalar_node mbnscmodelightcorr_scalar = SNMP_SCALAR_CREATE_NODE(13, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_OCTET_STRING, mbnscmode_treenode_get_value, mbnscmode_treenode_set_test, mbnscmode_treenode_set_value);

static const struct snmp_scalar_node mbnscmodeconfigcmd_scalar = SNMP_SCALAR_CREATE_NODE(100, SNMP_NODE_INSTANCE_READ_WRITE, SNMP_ASN1_TYPE_GAUGE, mbnscmode_treenode_get_value, mbnscmode_treenode_set_test, mbnscmode_treenode_set_value);

static const struct snmp_scalar_node mbnscmodeconfigchangedtime_scalar = SNMP_SCALAR_CREATE_NODE_READONLY(101, SNMP_ASN1_TYPE_TIMETICKS, mbnscmode_treenode_get_value);

static const struct snmp_node *const mbnscmode_subnodes[] = {
  &mbnscmodeswitchinfo_scalar.node.node,
  &mbnscmodedisplaybrightness_scalar.node.node,
  &mbnscmodedisplayformat_scalar.node.node,
  &mbnscmodedisplayalternate_scalar.node.node,
  &mbnscmodeirlock_scalar.node.node,
  &mbnscmodetimedispzeros_scalar.node.node,
  &mbnscmodedatedispzeros_scalar.node.node,
  &mbnscmodetempunit_scalar.node.node,
  &mbnscmodeclockopmode_scalar.node.node,
  &mbnscmodedispderating_scalar.node.node,
  &mbnscmodelightcorr_scalar.node.node,
  &mbnscadditionaldigitalclockmodes_treenode.node,
  &mbnscmodeconfigcmd_scalar.node.node,
  &mbnscmodeconfigchangedtime_scalar.node.node,
  &mbnscadditionalinterfacemodes_treenode.node
};
static const struct snmp_tree_node mbnscmode_treenode = SNMP_CREATE_TREE_NODE(4, mbnscmode_subnodes);

/* --- mobaNetClocksV2 1.3.6.1.4.1.13842.6.2 ----------------------------------------------------- */
static u16_t mbnsctime_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static snmp_err_t mbnsctime_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static snmp_err_t mbnsctime_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static const struct snmp_scalar_array_node_def mbnsctime_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscTimeNTP1 */ 
  {2, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscTimeNTP2 */ 
  {3, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscTimeNTP3 */ 
  {4, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscTimeNTP4 */ 
  {5, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeNTPcurrent */ 
  {6, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscTimeNTPpollIntervall */ 
  {7, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeDeviceTime */ 
  {8, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeLocOffset */ 
  {9, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeLastReception */ 
  {100, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscTimeConfigCmd */ 
  {101, SNMP_ASN1_TYPE_TIMETICKS, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeConfigChangedTime */ 
};
static const struct snmp_scalar_array_node mbnsctime_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(2, mbnsctime_scalars_nodes, mbnsctime_scalars_get_value, mbnsctime_scalars_set_test, mbnsctime_scalars_set_value);

static u16_t mbnsctimezone_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static snmp_err_t mbnsctimezone_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static snmp_err_t mbnsctimezone_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static const struct snmp_scalar_array_node_def mbnsctimezone_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeZoneVersion */ 
  {2, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscTimeZoneNumber */ 
  {3, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeZoneEntry1 */ 
  {4, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeZoneEntry2 */ 
  {5, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeZoneEntry3 */ 
  {6, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeZoneEntry4 */ 
  {7, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeZoneEntry5 */ 
  {8, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeZoneEntry6 */ 
  {9, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeZoneEntry7 */ 
  {100, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscTimeZoneConfigCmd */ 
  {101, SNMP_ASN1_TYPE_TIMETICKS, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscTimeZoneConfigChangedTime */ 
};
static const struct snmp_scalar_array_node mbnsctimezone_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(3, mbnsctimezone_scalars_nodes, mbnsctimezone_scalars_get_value, mbnsctimezone_scalars_set_test, mbnsctimezone_scalars_set_value);

static u16_t mbnscgeneral_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static snmp_err_t mbnscgeneral_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static snmp_err_t mbnscgeneral_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static const struct snmp_scalar_array_node_def mbnscgeneral_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscGeneralType */ 
  {2, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscGeneralName */ 
  {3, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscGeneralFirmwareNumber */ 
  {4, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscGeneralFirmwareVer */ 
  {5, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscGeneralStatus */ 
  {6, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscGeneralAlarms */ 
  {7, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscGeneralSlaveInfo1 */ 
  {8, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscGeneralSlaveInfo2 */ 
  {9, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscGeneralSlaveInfo3 */ 
  {100, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscGeneralConfigCmd */ 
  {101, SNMP_ASN1_TYPE_TIMETICKS, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscGeneralConfigChangedTime */ 
};
static const struct snmp_scalar_array_node mbnscgeneral_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(5, mbnscgeneral_scalars_nodes, mbnscgeneral_scalars_get_value, mbnscgeneral_scalars_set_test, mbnscgeneral_scalars_set_value);

static u16_t mbnscsupervision_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static snmp_err_t mbnscsupervision_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static snmp_err_t mbnscsupervision_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static const struct snmp_scalar_array_node_def mbnscsupervision_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscSNMPManager1 */ 
  {2, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscSNMPManager2 */ 
  {3, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscSNMPTrapAliveMsgInterval */ 
  {100, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscSNMPConfigCmd */ 
  {101, SNMP_ASN1_TYPE_TIMETICKS, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscSNMPConfigChangedTime */ 
};
static const struct snmp_scalar_array_node mbnscsupervision_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(6, mbnscsupervision_scalars_nodes, mbnscsupervision_scalars_get_value, mbnscsupervision_scalars_set_test, mbnscsupervision_scalars_set_value);

static u16_t mbnsccommand_scalars_get_value(const struct snmp_scalar_array_node_def *node, void *value);
static snmp_err_t mbnsccommand_scalars_set_test(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static snmp_err_t mbnsccommand_scalars_set_value(const struct snmp_scalar_array_node_def *node, u16_t len, void *value);
static const struct snmp_scalar_array_node_def mbnsccommand_scalars_nodes[] = {
  {1, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscCommand12Pos */ 
  {2, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscCommandSWReset */ 
  {3, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscCommandFactorySetting */ 
  {4, SNMP_ASN1_TYPE_OCTET_STRING, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscCommandFirmwUpd */ 
  {5, SNMP_ASN1_TYPE_INTEGER, SNMP_NODE_INSTANCE_READ_ONLY}, /* mbnscCommandExtContact */ 
  {100, SNMP_ASN1_TYPE_GAUGE, SNMP_NODE_INSTANCE_READ_WRITE}, /* mbnscCommandConfigCmd */ 
};
static const struct snmp_scalar_array_node mbnsccommand_scalars = SNMP_SCALAR_CREATE_ARRAY_NODE(7, mbnsccommand_scalars_nodes, mbnsccommand_scalars_get_value, mbnsccommand_scalars_set_test, mbnsccommand_scalars_set_value);

static const struct snmp_node *const mobanetclocksv2_subnodes[] = {
  &mbnscnet_treenode.node,
  &mbnsctime_scalars.node.node,
  &mbnsctimezone_scalars.node.node,
  &mbnscmode_treenode.node,
  &mbnscgeneral_scalars.node.node,
  &mbnscsupervision_scalars.node.node,
  &mbnsccommand_scalars.node.node
};
static const struct snmp_tree_node mobanetclocksv2_treenode = SNMP_CREATE_TREE_NODE(2, mobanetclocksv2_subnodes);

/* --- mobaNetClocks 1.3.6.1.4.1.13842.6 ----------------------------------------------------- */
static const struct snmp_node *const mobanetclocks_subnodes[] = {
  &mobanetclocksv2_treenode.node
};
static const struct snmp_tree_node mobanetclocks_treenode = SNMP_CREATE_TREE_NODE(6, mobanetclocks_subnodes);

/* --- mobatime  ----------------------------------------------------- */
static const struct snmp_node *const mobatime_subnodes[] = {
  &mobanetclocks_treenode.node
};
static const struct snmp_tree_node mobatime_root = SNMP_CREATE_TREE_NODE(13842, mobatime_subnodes);
static const u32_t mobatime_base_oid[] = {1,3,6,1,4,1,13842};
const struct snmp_mib mobatime = {mobatime_base_oid, LWIP_ARRAYSIZE(mobatime_base_oid), &mobatime_root.node};



/*
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
LWIP MIB generator - preserved section begin
Code below is preserved on regeneration. Remove these comment lines to regenerate code.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*/

/* --- mbnscMIB  ----------------------------------------------------- */
/* --- mbnscnet 1.3.6.1.4.1.13842.6.2.1 ----------------------------------------------------- */
/* --- mbnscadditionaldigitalclockmodes 1.3.6.1.4.1.13842.6.2.4.30 ----------------------------------------------------- */
/* --- mbnscnmi 1.3.6.1.4.1.13842.6.2.4.40.1 ----------------------------------------------------- */
static u16_t mbnscnmi_treenode_get_value(struct snmp_node_instance *instance, void *value)
{
   u16_t value_len;

   switch (instance->node->oid)
   {
      case 1:
         {
            /* mbnscnmidcfcurrentloop */
            s32_t *v = (s32_t *)value;

            /* TODO: put requested value to '*v' here */
            value_len = sizeof(s32_t);
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 2:
         {
            /* mbnscnmilinedriver */
            s32_t *v = (s32_t *)value;

            /* TODO: put requested value to '*v' here */
            value_len = sizeof(s32_t);
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 3:
         {
            /* mbnscnmimobalinemode */
            s32_t *v = (s32_t *)value;

            /* TODO: put requested value to '*v' here */
            value_len = sizeof(s32_t);
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 4:
         {
            /* mbnscnmimobalineminutehandmode */
            s32_t *v = (s32_t *)value;

            /* TODO: put requested value to '*v' here */
            value_len = sizeof(s32_t);
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 5:
         {
            /* mbnscnmiactivedcfmode */
            s32_t *v = (s32_t *)value;

            /* TODO: put requested value to '*v' here */
            value_len = sizeof(s32_t);
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 100:
         {
            /* mbnscnmiconfigcmd */
            u32_t *v = (u32_t *)value;

            /* TODO: put requested value to '*v' here */
            value_len = sizeof(u32_t);
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 101:
         {
            /* mbnscnmiconfigchangedtime */
            u32_t *v = (u32_t *)value;

            /* TODO: put requested value to '*v' here */
            value_len = sizeof(u32_t);
            LWIP_UNUSED_ARG(v);
         }
         break;
      default:
         {
            LWIP_DEBUGF(SNMP_MIB_DEBUG,("mbnscnmi_treenode_get_value(): unknown id: %"S32_F"\n", instance->node->oid));
            value_len = 0;
         }
         break;
   }
   return value_len;
}
static snmp_err_t mbnscnmi_treenode_set_test(struct snmp_node_instance *instance, u16_t len, void *value)
{
   snmp_err_t err = SNMP_ERR_WRONGVALUE;

   switch (instance->node->oid)
   {
      case 1:
         {
            /* mbnscnmidcfcurrentloop */
            s32_t *v = (s32_t *)value;

            LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
            if (((*v >= 0) && (*v <= 1)))
            {
               err = SNMP_ERR_NOERROR;
            }
         }
         break;
      case 2:
         {
            /* mbnscnmilinedriver */
            s32_t *v = (s32_t *)value;

            LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
            if (((*v >= 0) && (*v <= 2)))
            {
               err = SNMP_ERR_NOERROR;
            }
         }
         break;
      case 3:
         {
            /* mbnscnmimobalinemode */
            s32_t *v = (s32_t *)value;

            LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
            if (((*v >= 0) && (*v <= 2)))
            {
               err = SNMP_ERR_NOERROR;
            }
         }
         break;
      case 4:
         {
            /* mbnscnmimobalineminutehandmode */
            s32_t *v = (s32_t *)value;

            LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
            if (((*v >= 0) && (*v <= 2)))
            {
               err = SNMP_ERR_NOERROR;
            }
         }
         break;
      case 5:
         {
            /* mbnscnmiactivedcfmode */
            s32_t *v = (s32_t *)value;

            LWIP_ASSERT("Invalid length for datatype", (len == sizeof(s32_t)));
            if (((*v >= 1) && (*v <= 6)))
            {
               err = SNMP_ERR_NOERROR;
            }
         }
         break;
      case 100:
         {
            /* mbnscnmiconfigcmd */
            u32_t *v = (u32_t *)value;

            LWIP_ASSERT("Invalid length for datatype", (len == sizeof(u32_t)));
            if (((*v >= 0) && (*v <= 2)))
            {
               err = SNMP_ERR_NOERROR;
            }
         }
         break;
      default:
         {
            LWIP_DEBUGF(SNMP_MIB_DEBUG,("mbnscnmi_treenode_set_test(): unknown id: %"S32_F"\n", instance->node->oid));
         }
         break;
   }
   return err;
}
static snmp_err_t mbnscnmi_treenode_set_value(struct snmp_node_instance *instance, u16_t len, void *value)
{
   snmp_err_t err = SNMP_ERR_NOERROR;

   LWIP_UNUSED_ARG(len);
   switch (instance->node->oid)
   {
      case 1:
         {
            /* mbnscnmidcfcurrentloop */
            s32_t *v = (s32_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 2:
         {
            /* mbnscnmilinedriver */
            s32_t *v = (s32_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 3:
         {
            /* mbnscnmimobalinemode */
            s32_t *v = (s32_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 4:
         {
            /* mbnscnmimobalineminutehandmode */
            s32_t *v = (s32_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 5:
         {
            /* mbnscnmiactivedcfmode */
            s32_t *v = (s32_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 100:
         {
            /* mbnscnmiconfigcmd */
            u32_t *v = (u32_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      default:
         {
            LWIP_DEBUGF(SNMP_MIB_DEBUG,("mbnscnmi_treenode_set_value(): unknown id: %"S32_F"\n", instance->node->oid));
         }
         break;
   }
   return err;
}

/* --- mbnscadditionalinterfacemodes 1.3.6.1.4.1.13842.6.2.4.40 ----------------------------------------------------- */
/* --- mbnscmode 1.3.6.1.4.1.13842.6.2.4 ----------------------------------------------------- */
static u16_t mbnscmode_treenode_get_value(struct snmp_node_instance *instance, void *value)
{
   u16_t value_len;

   switch (instance->node->oid)
   {
      case 1:
         {
            /* mbnscmodeswitchinfo */
            s32_t *v = (s32_t *)value;

            /* TODO: put requested value to '*v' here */
            value_len = sizeof(s32_t);
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 2:
         {
            /* mbnscmodedisplaybrightness */
            u8_t *v = (u8_t *)value;

            /* TODO: take care that value with variable length fits into buffer: (value_len <= SNMP_MAX_VALUE_SIZE) */
            /* TODO: take care of len restrictions defined in MIB: ((value_len >= 0) && (value_len <= 255)) */
            /* TODO: put requested value to '*v' here */
            value_len = 0;
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 3:
         {
            /* mbnscmodedisplayformat */
            u8_t *v = (u8_t *)value;

            /* TODO: take care that value with variable length fits into buffer: (value_len <= SNMP_MAX_VALUE_SIZE) */
            /* TODO: take care of len restrictions defined in MIB: ((value_len >= 0) && (value_len <= 255)) */
            /* TODO: put requested value to '*v' here */
            value_len = 0;
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 4:
         {
            /* mbnscmodedisplayalternate */
            u8_t *v = (u8_t *)value;

            /* TODO: take care that value with variable length fits into buffer: (value_len <= SNMP_MAX_VALUE_SIZE) */
            /* TODO: take care of len restrictions defined in MIB: ((value_len >= 0) && (value_len <= 255)) */
            /* TODO: put requested value to '*v' here */
            value_len = 0;
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 6:
         {
            /* mbnscmodeirlock */
            u8_t *v = (u8_t *)value;

            /* TODO: take care that value with variable length fits into buffer: (value_len <= SNMP_MAX_VALUE_SIZE) */
            /* TODO: take care of len restrictions defined in MIB: ((value_len >= 0) && (value_len <= 255)) */
            /* TODO: put requested value to '*v' here */
            value_len = 0;
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 7:
         {
            /* mbnscmodetimedispzeros */
            u8_t *v = (u8_t *)value;

            /* TODO: take care that value with variable length fits into buffer: (value_len <= SNMP_MAX_VALUE_SIZE) */
            /* TODO: take care of len restrictions defined in MIB: ((value_len >= 0) && (value_len <= 255)) */
            /* TODO: put requested value to '*v' here */
            value_len = 0;
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 8:
         {
            /* mbnscmodedatedispzeros */
            u8_t *v = (u8_t *)value;

            /* TODO: take care that value with variable length fits into buffer: (value_len <= SNMP_MAX_VALUE_SIZE) */
            /* TODO: take care of len restrictions defined in MIB: ((value_len >= 0) && (value_len <= 255)) */
            /* TODO: put requested value to '*v' here */
            value_len = 0;
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 9:
         {
            /* mbnscmodetempunit */
            u8_t *v = (u8_t *)value;

            /* TODO: take care that value with variable length fits into buffer: (value_len <= SNMP_MAX_VALUE_SIZE) */
            /* TODO: take care of len restrictions defined in MIB: ((value_len >= 0) && (value_len <= 255)) */
            /* TODO: put requested value to '*v' here */
            value_len = 0;
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 10:
         {
            /* mbnscmodeclockopmode */
            u8_t *v = (u8_t *)value;

            /* TODO: take care that value with variable length fits into buffer: (value_len <= SNMP_MAX_VALUE_SIZE) */
            /* TODO: take care of len restrictions defined in MIB: ((value_len >= 0) && (value_len <= 255)) */
            /* TODO: put requested value to '*v' here */
            value_len = 0;
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 12:
         {
            /* mbnscmodedispderating */
            u8_t *v = (u8_t *)value;

            /* TODO: take care that value with variable length fits into buffer: (value_len <= SNMP_MAX_VALUE_SIZE) */
            /* TODO: take care of len restrictions defined in MIB: ((value_len >= 0) && (value_len <= 255)) */
            /* TODO: put requested value to '*v' here */
            value_len = 0;
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 13:
         {
            /* mbnscmodelightcorr */
            u8_t *v = (u8_t *)value;

            /* TODO: take care that value with variable length fits into buffer: (value_len <= SNMP_MAX_VALUE_SIZE) */
            /* TODO: take care of len restrictions defined in MIB: ((value_len >= 0) && (value_len <= 255)) */
            /* TODO: put requested value to '*v' here */
            value_len = 0;
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 100:
         {
            /* mbnscmodeconfigcmd */
            u32_t *v = (u32_t *)value;

            /* TODO: put requested value to '*v' here */
            value_len = sizeof(u32_t);
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 101:
         {
            /* mbnscmodeconfigchangedtime */
            u32_t *v = (u32_t *)value;

            /* TODO: put requested value to '*v' here */
            value_len = sizeof(u32_t);
            LWIP_UNUSED_ARG(v);
         }
         break;
      default:
         {
            LWIP_DEBUGF(SNMP_MIB_DEBUG,("mbnscmode_treenode_get_value(): unknown id: %"S32_F"\n", instance->node->oid));
            value_len = 0;
         }
         break;
   }
   return value_len;
}
static snmp_err_t mbnscmode_treenode_set_test(struct snmp_node_instance *instance, u16_t len, void *value)
{
   snmp_err_t err = SNMP_ERR_WRONGVALUE;

   switch (instance->node->oid)
   {
      case 2:
         {
            /* mbnscmodedisplaybrightness */
            u8_t *v = (u8_t *)value;

            if (((len >= 0) && (len <= 255)))
            {
               err = SNMP_ERR_NOERROR;
            }
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 3:
         {
            /* mbnscmodedisplayformat */
            u8_t *v = (u8_t *)value;

            if (((len >= 0) && (len <= 255)))
            {
               err = SNMP_ERR_NOERROR;
            }
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 4:
         {
            /* mbnscmodedisplayalternate */
            u8_t *v = (u8_t *)value;

            if (((len >= 0) && (len <= 255)))
            {
               err = SNMP_ERR_NOERROR;
            }
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 6:
         {
            /* mbnscmodeirlock */
            u8_t *v = (u8_t *)value;

            if (((len >= 0) && (len <= 255)))
            {
               err = SNMP_ERR_NOERROR;
            }
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 7:
         {
            /* mbnscmodetimedispzeros */
            u8_t *v = (u8_t *)value;

            if (((len >= 0) && (len <= 255)))
            {
               err = SNMP_ERR_NOERROR;
            }
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 8:
         {
            /* mbnscmodedatedispzeros */
            u8_t *v = (u8_t *)value;

            if (((len >= 0) && (len <= 255)))
            {
               err = SNMP_ERR_NOERROR;
            }
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 9:
         {
            /* mbnscmodetempunit */
            u8_t *v = (u8_t *)value;

            if (((len >= 0) && (len <= 255)))
            {
               err = SNMP_ERR_NOERROR;
            }
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 10:
         {
            /* mbnscmodeclockopmode */
            u8_t *v = (u8_t *)value;

            if (((len >= 0) && (len <= 255)))
            {
               err = SNMP_ERR_NOERROR;
            }
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 12:
         {
            /* mbnscmodedispderating */
            u8_t *v = (u8_t *)value;

            if (((len >= 0) && (len <= 255)))
            {
               err = SNMP_ERR_NOERROR;
            }
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 13:
         {
            /* mbnscmodelightcorr */
            u8_t *v = (u8_t *)value;

            if (((len >= 0) && (len <= 255)))
            {
               err = SNMP_ERR_NOERROR;
            }
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 100:
         {
            /* mbnscmodeconfigcmd */
            u32_t *v = (u32_t *)value;

            LWIP_ASSERT("Invalid length for datatype", (len == sizeof(u32_t)));
            if (((*v >= 0) && (*v <= 2)))
            {
               err = SNMP_ERR_NOERROR;
            }
         }
         break;
      default:
         {
            LWIP_DEBUGF(SNMP_MIB_DEBUG,("mbnscmode_treenode_set_test(): unknown id: %"S32_F"\n", instance->node->oid));
         }
         break;
   }
   return err;
}
static snmp_err_t mbnscmode_treenode_set_value(struct snmp_node_instance *instance, u16_t len, void *value)
{
   snmp_err_t err = SNMP_ERR_NOERROR;

   LWIP_UNUSED_ARG(len);
   switch (instance->node->oid)
   {
      case 2:
         {
            /* mbnscmodedisplaybrightness */
            u8_t *v = (u8_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 3:
         {
            /* mbnscmodedisplayformat */
            u8_t *v = (u8_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 4:
         {
            /* mbnscmodedisplayalternate */
            u8_t *v = (u8_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 6:
         {
            /* mbnscmodeirlock */
            u8_t *v = (u8_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 7:
         {
            /* mbnscmodetimedispzeros */
            u8_t *v = (u8_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 8:
         {
            /* mbnscmodedatedispzeros */
            u8_t *v = (u8_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 9:
         {
            /* mbnscmodetempunit */
            u8_t *v = (u8_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 10:
         {
            /* mbnscmodeclockopmode */
            u8_t *v = (u8_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 12:
         {
            /* mbnscmodedispderating */
            u8_t *v = (u8_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 13:
         {
            /* mbnscmodelightcorr */
            u8_t *v = (u8_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      case 100:
         {
            /* mbnscmodeconfigcmd */
            u32_t *v = (u32_t *)value;

            /* TODO: store new value contained in '*v' here */
            LWIP_UNUSED_ARG(v);
         }
         break;
      default:
         {
            LWIP_DEBUGF(SNMP_MIB_DEBUG,("mbnscmode_treenode_set_value(): unknown id: %"S32_F"\n", instance->node->oid));
         }
         break;
   }
   return err;
}

/* --- mobanetclocksv2 1.3.6.1.4.1.13842.6.2 ----------------------------------------------------- */
/* --- mobanetclocks 1.3.6.1.4.1.13842.6 ----------------------------------------------------- */
/* --- mobatime  ----------------------------------------------------- */
/* --- mobaNetClocks  ----------------------------------------------------- */
/* --- mobaNetClocksV2  ----------------------------------------------------- */
/* --- mbnscNet  ----------------------------------------------------- */
/* --- mbnscNetGen  ----------------------------------------------------- */
/* --- mbnscNetIPv4  ----------------------------------------------------- */
/* --- mbnscNetIPv6  ----------------------------------------------------- */
/* --- mbnscTime  ----------------------------------------------------- */
/* --- mbnscTimeZone  ----------------------------------------------------- */
/* --- mbnscMode  ----------------------------------------------------- */
/* --- mbnscAdditionalDigitalClockModes  ----------------------------------------------------- */
/* --- mbnscSensors  ----------------------------------------------------- */
/* --- mbnscDA  ----------------------------------------------------- */
/* --- mbnscDK  ----------------------------------------------------- */
/* --- mbnscAdditionalInterfaceModes  ----------------------------------------------------- */
/* --- mbnscNMI  ----------------------------------------------------- */
/* --- mbnscNMISideClockState  ----------------------------------------------------- */
/* --- mbnscGeneral  ----------------------------------------------------- */
/* --- mbnscSupervision  ----------------------------------------------------- */
/* --- mbnscCommand  ----------------------------------------------------- */
/* --- mbnscSnmpConfig  ----------------------------------------------------- */
/* --- mbnscSnmpCurrentAlarmInfo  ----------------------------------------------------- */
/* --- mbnscTraps  ----------------------------------------------------- */
#endif /* LWIP_SNMP */
