/*
Generated by LwipMibCompiler
*/

#ifndef MOBANETCLOCKSV2_MIB_H
#define MOBANETCLOCKSV2_MIB_H MOBANETCLOCKSV2_MIB_H

#include "lwip/apps/snmp_opts.h"
#if LWIP_SNMP

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#include "lwip/apps/snmp_core.h"

extern const struct snmp_mib mobatime;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* LWIP_SNMP */
#endif /* MOBANETCLOCKSV2_MIB_H */
